import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { RoomsService } from '@rooms/rooms.service';
import { RoomsController } from '@rooms/rooms.controller';
import { Room } from '@rooms/room.model';

@Module({
  imports: [SequelizeModule.forFeature([Room])],
  providers: [RoomsService],
  controllers: [RoomsController],
  // exports:[SequelizeModule]
})
export class RoomsModule {}

// If you want to use the repository outside of the module which imports SequelizeModule.forFeature, you'll need to re-export the providers generated by it. You can do this by exporting the whole module, ref https://docs.nestjs.com/techniques/database
